extends Control

# events generated by the players actions
const click_on_territory := 'overworld.click_on_territory'
const click_on_map := 'overworld.click_on_map'
const right_click := 'overworld.right_click'
const click_on_inspect := 'overworld.click_on_inspect'
const rest := 'overworld.rest'
const invade := 'overworld.invade'
const turn_end := 'overworld.turn_end'
# events generated by the game
const win_territory := 'overworld.win_territory'
const all_territories_taken := 'overworld.all_territories_taken'

# Called when the node enters the scene tree for the first time.
func _ready():
	print("ready: overworld")
	
	var test := Empire.new()
	test.leader = Territory.Unused.name
	test.territories = [Territory.all[1], Territory.all[3], Territory.all[5]]
	var v = test.get_adjacent()
	for e in v:
		print(e.name)
	
# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
